src/browser/extension/background/messaging.js, src/browser/extension/devpanel/index.js, src/browser/extension/devpanel/remote.js, src/browser/extension/inject/contentScript.js, src/browser/extension/inject/index.js, src/browser/extension/manifest.json, webpack/base.config.js
Added support for external messaging, so it is possible to use devtools for any chrome-based application.
Unlike web apps, Chrome extension doesn't inject anything in other chrome extensions or in chrome / electron / nw.js apps, so you have to do it by yourself to allow debugging. Just add:
```
<script src="chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/inject.bundle.js"></script>
```
=> Support for chrome / electron / nw.js apps and extensions

gulpfile.babel.js
Currently, only JavaScript code is watched for changes. The modifications in Jade files or static assets aren’t noticed until gulp is restarted. I’ve added `views:watch` and `copy:watch` tasks to resolve this. Looking forward to your comments.
=> Add Gulp watch tasks

src/browser/extension/manifest.json
Adds the "all_frames" option to the manifest.json to allow DevTools to access iframes that might hold the Store instead of the main page.
Solves: https://github.com/zalmoxisus/redux-devtools-extension/issues/50
=> Allow DevTools to access the frames

package.json, src/app/containers/Monitor.js, src/browser/extension/options/monitors.js
Adds [redux-devtools-inspector](https://github.com/alexkuz/redux-devtools-inspector) as another side monitor.
=> add redux-devtools-inspector monitor

README.md, src/app/store/configureStore.js, src/browser/extension/inject/pageScript.js
Adds desirialize callbacks ([https://github.com/gaearon/redux-devtools/blob/ccb3f2f07040561b8ae4b307767f745be3b9cc96/src/persistState.js#L4](https://github.com/gaearon/redux-devtools/blob/ccb3f2f07040561b8ae4b307767f745be3b9cc96/src/persistState.js#L4)) for persistState as config arguments.
If you approve it, I can update config arguments part in README
=> add deserialize callbacks for persistState

package.json, src/browser/extension/background/contextMenus.js, src/browser/extension/background/index.js, src/browser/extension/background/messaging.js, src/browser/extension/devpanel/index.js, src/browser/extension/inject/contentScript.js, src/browser/extension/inject/pageScript.js, src/browser/extension/window/index.js
Due to Chrome restrictions, the extension is not allowed to communicate with the app's script directly, so we relay every change to the background script. By introducing new features in #60, the serialization for every change [becomes slower](https://github.com/zalmoxisus/redux-devtools-extension/issues/67#issuecomment-191364884), which is [a problem when having a lot of data in states](https://twitter.com/tjholowaychuk/status/707283606763229184).
We want the extension not to process the changes while it is not required as most of the time we don't monitor the changes.
The problem is to support simultaneous instances in this scenario, so we need to change the way of messaging by using long-lived connections.
=> The extension shouldn't affect the performance when no monitors are opened

README.md, src/browser/extension/inject/pageScript.js
I think it is much more convenient to set these options in `window.devToolsExtension()` config.
=> Add actionsBlacklist and actionsWhitelist config options

package.json, src/app/containers/Monitor.js, src/browser/extension/background/messaging.js
Note: if `shouldPersistState` is enabled, `monitorState` is not updated, and `stagedActionIds` list seems to be broken.
=> update Inspector Monitor

src/app/containers/App.js, src/browser/extension/background/messaging.js
Related to #135, it's only for devpanel.
Tested with [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate)
Known some chrome.* API Electron not supported:
* chrome.notifications
* chrome.runtime.onConnectExternal
* chrome.runtime.onMessageExternal
=> Support Electron DevTools extension

gulpfile.babel.js
Currently it has `ERR_FILE_NOT_FOUND` errors, it looks css files not included in v2.2.0.
=> Fix production copy path in gulpfile

README.md
Developers who never used the 'compose' feature before might be interested to know that it is part of 'redux'. Same goes for other functions used in the example code.
Add a line to the sample code in the readme explaining where used components come from.
```javascript
import { createStore, applyMiddleware, compose } from 'redux';
```
I for one just spend 10 minutes going through the issues until I found a snippet in #110 that pointed me the right way. And though the full code of the `configureStore` linked in the readme could have provided me the same information. It seems to me that we could save a lot of developers a lot of time by simply adding this one line to the readme.
=> Explain where used functions come from.

src/app/containers/App.js
Related to https://github.com/chentsulin/electron-react-boilerplate/issues/259.
The `chrome.storage.local` is not supported on Electron.
=> Fix local storage on Electron

.eslintrc, package.json, src/app/containers/App.js, src/browser/extension/background/messaging.js, src/browser/extension/options/index.js
This should fix #150 .
However, when I tried to run `npm run compress:extension`, it shows an error:
```
ERROR in ./src/app/containers/App.js
Module not found: Error: Cannot resolve module 'remotedev-app/lib/components/TestGenerator' in ……/redux-devtools-extension/src/app/containers
@ ./src/app/containers/App.js 56:21-74
```
Other than that it looks good.
=> Fix eslint errors

src/app/containers/App.js, src/browser/extension/background/messaging.js, src/browser/extension/electronMock.js, webpack/base.config.js
Related to https://github.com/zalmoxisus/redux-devtools-extension/pull/149#issuecomment-229249892, the code will be cleaner.
=> Add fake chrome.* API for Electron

appveyor.yml, package.json, src/browser/extension/background/contextMenus.js, src/browser/extension/electronMock.js, test/electron/devpanel.spec.js, webpack/base.config.js
The `chrome.runtime.sendMessage` is related to https://github.com/chentsulin/electron-react-boilerplate/issues/266.
The `chrome.storage.local` is officially supported on v1.2.6, we can check it exists.
=> Update Electron mock

README.md
I've turned my [complaints](https://github.com/zalmoxisus/redux-devtools-extension/issues/161) into some minor changes in the Readme. 
Since I couldn't find store-initialization via a function ("configureStore") anywhere in the redux-docs, I've removed it from all examples, imho this is more transparent.
=> Simpler examples for implementation-docs, in accordance with redux-docs

package.json
`rm` is absent on Windows, and the tests fail because of this.
=> Replace `rm` with `rimraf`

docs/Troubleshooting.md
In Chrome you must explicitly enable the extension access to file:/// URLs, otherwise it won’t work locally.
It’s currently not an issue in Firefox, because Firefox allows all URLs by default (but this my change in the future?).
=> Add instruction for working with file:/// URLs

docs/FAQ.md, gulpfile.babel.js, src/browser/extension/inject/deprecatedWarn.js, src/browser/extension/inject/index.js, src/browser/extension/manifest.json, src/browser/firefox/manifest.json, webpack/base.config.js
To avoid problems like https://github.com/jhen0409/react-chrome-extension-boilerplate/issues/50, we can provide a better filename for inject bundle.
=> Deprecated `inject.bundle.js`, use `redux-devtools-extension.js` instead

docs/API/Arguments.md, src/app/api/filters.js, src/app/api/index.js, src/browser/extension/inject/pageScript.js
When having frequently dispatched actions, we want to batch them instead of flooding the extension and consuming all the cpu. 
Now we're having a new parameter for that: **latency** (*number (in ms)*) - if more than one action is dispatched in this interval, all new actions will be collected and sent at once. It determines the performance vs speed. When setting it to `0`, all actions will be sent instantly. Default is `500 ms`.
The demo bellow was consuming 100% of cpu before, but now it's less than 30% (most of which being taken by React) with the default latency. By increasing further, we can avoid cpu spikes at all.
=> Add latency to improve the performance

README.md
Now backers and sponsors from opencollective will appear directly on your readme, see for example https://github.com/webpack/webpack#backers for an idea of how it may look. 
Also added badges on top. 
User guide (https://github.com/opencollective/opencollective/wiki/User-Guide) in case you want to customize:
=> added backers and sponsors

src/browser/extension/chromeAPIMock.js
Currently I getting error `chrome.storage.local.remove is not a function` when I toggle dispatcher or slider on Electron, It doesn't crash just print log in the main process.
I also submit a PR to Electron (https://github.com/electron/electron/pull/7923), but I think we can backward compatibility.
=> Add `chrome.storage.local.remove` mock for Electron

src/app/api/generateInstanceId.js, src/app/api/index.js, src/app/containers/App.js, src/app/middlewares/api.js, src/app/middlewares/panelSync.js, src/app/middlewares/windowSync.js, src/app/reducers/background/index.js, src/app/reducers/background/persistStates.js, src/browser/extension/background/openWindow.js, src/browser/extension/inject/contentScript.js, src/browser/extension/inject/pageScript.js
Currently the extension is adding [`persistState` enhancer](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js), which store every change in `localStorage`. However, it has issues with:
- [filling up local storage very quickly](https://github.com/gaearon/redux-devtools/issues/298)
- [changing url](https://github.com/zalmoxisus/redux-devtools-extension/issues/274)
- [throwing on unserializable data](https://github.com/gaearon/redux-devtools/issues/262).
We already have all the data from the store on the extension part, and can easily restore it without `persistState` enhancer. This PR adds a new button:
By toggling the button, the states won't be removed from the monitor on unloading the page and will be restored on reload:
We should show when the button is toggled, …
=> Persist states right from the extension

docs/Integrations.md
The ember-redux repo has been moved under and organization. We also recently removed the browserify requirement so I've updated the enhancer to be v2.0.0 friendly
=> [Integrations]: updated ember-redux example and link

docs/FAQ.md
Unfortunately, Chrome 54 and onward no longer support Panels. The feature should probably be removed from DevTools and this FAQ. See: http://www.ghacks.net/2016/10/19/google-removes-panel-support-from-chrome/
See also #313
=> Remove reference to Chrome Panels

README.md
Correct note about usage in production: changing `react-create-app` to `create-react-app` and linking to the corresponding section of `create-react-app`'s `webpack.config.prod.js`.
=> Fix typo, link to `create-react-app` config

docs/Integrations.md
As suggested [here](https://github.com/zalmoxisus/redux-devtools-extension/issues/288#issuecomment-273890896) this PR adds katana monitor to the dev tools list
=> Add Katana Monitor to dev tools list

src/browser/extension/devpanel/index.js
The DevTools panel work has landed in Fx 54 (DevEdition) and seems to be working well for Redux DevTools.  
I found one issue, reported in #9 https://github.com/zalmoxisus/redux-devtools-extension/issues/9#issuecomment-298416062 and this PR fixes that by guarding against the currently unimplemented `devtools.inspectedWindow.getResources` call which isn't needed for Firefox anyway.
=> Open a devtools panel in Firefox

npm-package/developmentOnly.d.ts, npm-package/index.d.ts, npm-package/logOnly.d.ts, npm-package/logOnlyInProduction.d.ts, npm-package/package.json
Sorry, my previous PR did not work with the submodules (e.g. `redux-devtools-extension/developmentOnly`) because I didn't use those, this fixes that.
=> Fix submodule typings

src/app/api/index.js
During connection initialization, state is not serialized with respect to serialization options.
This simple fix is sending proper serialization options to `stringify`.
Edit: also added missing reviver in `getSeralizeParameter`. I added it for immutable serialization also, but I am not using ImmutableJS, so someone should double check if it is needed there. By analogy, it seems it is.
=> fix passing wrong serialization config on init

package.json, test/.eslintrc, test/electron/devpanel.spec.js, yarn.lock
Update E2E test for latest version (1.6.6) of Electron, a little different is `WebInspector` instance in devtools have been renamed to `UI`.
=> Update E2E test for Electron 1.6

package.json, src/browser/extension/inject/pageScriptWrap.js, webpack/base.config.js, webpack/dev.config.js
On a hunch, I thought this might speed up script parsing and execution times, which applies to every page loaded by the browser when the extension is enabled.
Results are... inconclusive, but testing was mainly loading [Lighthouse homepage](https://developers.google.com/web/tools/lighthouse/) and [bash.org](http://bash.org/) and refreshing the Performance tab. Read my [stream of consciousness following this thread](https://twitter.com/grrowl/status/883522109837791233). Tested as the chrome extension
=> Update to Webpack 3

src/app/api/index.js
If a payload contains a reference to a cross-domain iframe window, it may break serialization.
Rather than give up on serialization altogether, try to avoid serializing any window objects if they are found.  I think this is probably fine in most cases, I doubt anyone purposely passes a window object in a redux action.
=> don't serialize window objects, fixes #337

npm-package/index.d.ts
GenericStoreEnhancer is deprecated and was renamed to StoreEnhancer.
=> GenericStoreEnhancer isn't a exported member from redux.

npm-package/index.d.ts
Related to #519, it's a fix for any projects still used Redux `v3`. Also tested with Redux `v4`.
=> Add required type for StoreEnhancer in type definition of npm package

src/browser/extension/inject/pageScript.js
The way how redux applying middlewares (monkey patching), custom middleware able to handle more than first argument of dispatch method. It's really useful in some cases to simplify code.
This fix update "dispatch" method to allow such middlewares work properly
=> Unblock dispatch arguments

src/browser/extension/background/contextMenus.js, src/browser/extension/background/index.js, src/browser/extension/options/ContextMenuGroup.js, src/browser/extension/options/Options.js, src/browser/extension/options/syncOptions.js
Resolve #265 #471 
Added an option to switch whether context menu display or not.
=> Provide an option to hide context menu

npm-package/index.d.ts
Typing `funcs` and StoreEnhancer as a generic of `any` causes anything using the result to lose typings.
This restores the typings to the resulting StoreEnhancer
=> Restore store typings (Fix #539)

src/app/middlewares/api.js, src/browser/extension/inject/contentScript.js
As discussed in #566 and #543, Chrome added a limit on messages, so we're splitting bigger object parts into chunks. However by increasing the sate, the extension will have out-of-memory crash at some point, so in future versions we need an option to run devtools from the client part, not from devpanel or extension window.
Here we're splitting messages only from content script to the background script. There is no need to do that also from background script to devpanel after #580 is merged.
=> Workaround for new Chrome limit on message size

README.md, docs/Integrations.md
- Links pointing to the docs website
- Update implementation to complement new NgRx versions
=> Update NgRx Integration example

npm-package/index.d.ts
The TypeScript definition file was missing `trace` and `traceLimit` in the `composeWithDevTools()` options type, making it a TypeScript error to pass these options. This PR adds them.
=> Add trace options to TypeScript definition file

docs/Integrations.md
Integration with reductive has been released.
https://github.com/ambientlight/reductive-dev-tools
Feature coverage is as following: 
| feature | reductive | reducer component |
|---------|-----------|-------------------|
| pause   | ✔         | ✔                 |
| lock    |    [redux-devtools-extension/#618](https://github.com/zalmoxisus/redux-devtools-extension/issues/618)       |     [redux-devtools-extension/#618](https://github.com/zalmoxisus/redux-devtools-extension/issues/618)              |
| persist | ✔         | ✔                 |
| export  | ✔         | ✔                 |
| import  | ✔         | ✔                 |
| jump    | ✔         | ✔                 |
| skip    | ✔         | [#1](https://github.com/ambientlight/reductive-dev-tools/issues/1)|
| sweep | …
=> Added reductive into integrations

README.md
Added 'or' to the second line of chrome install instructions to imply chrome webstore is a one step process, and match installation conventions in README.md
=> (docs only) instructions no longer imply installation with webstore requires 2 steps

docs/Recipes.md
Additional example in documentation. How to avoid any without installing redux-devtools-extension npm package.
=> Add an example how to avoid any

README.md
The correct possessive form of "Redux" is "Redux's", not "Redux'".
Sources:
* https://ell.stackexchange.com/questions/6295/when-a-word-ends-in-s-or-x-do-you-add-s-or-just-an
* https://www.dictionary.com/e/how-do-you-use-an-apostrophe/
=> Correct possessive of "Redux"

README.md
Code of the package runs in production,
thus we should install it with `--save`, not with `--save-dev`
fixes #681
=> [docs] Suggest to install lib as prod dependency
